# Generated by Django 5.0.3 on 2024-03-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest_host',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
