# Generated by Django 5.0.3 on 2024-03-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_guest_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
